# Generated by Django 5.2.13 on 2026-06-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='review_data',
            field=models.TextField(blank=True, default=''),
        ),
    ]
